name: Build All
on: 
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Build GH Pages
        run: ./build.sh
      - name: GitHub Pages
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: ghpages
      - name: Build docker image
        run: |
          docker build -t curs/asciidoctor-idgen .
      - name: Log in to Docker Hub
        if: success() && github.ref == 'refs/heads/master'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        if: success() && github.ref == 'refs/heads/master'
        run: |
          docker push curs/asciidoctor-idgen:latest
